### PR TITLE
added configurable node name to be broadcast with version

### PR DESCRIPTION
**Pull request by nickycakes**

### CODE REVIEW

**Comment by cyyber** [comment]
Version name and node name could be rather passed as json format which would use to retrieve the data on receivers side by key, instead of hard coding it via data[:40]. Because in case the version name and node name becomes shorter, it could result into bug.

**Comment by nickycakes** [comment]
data[:40] just truncates the node name in case someone sets a really long one

**Comment by cyyber** [comment]
Lets say
self.factory.chain.version_number = "alpha/0.11a"
c.node_name = "Node-1"

then the data sent would be
"alpha/0.11a Node-1"

self.version = str(data)[:40] = "alpha/0.11a Node-1"

and the following line of code
printL((self.transport.getPeer().host, 'version: ', data))

would result into
x.x.x.x version: "alpha/0.11a Node-1"

I recommend to replace below
self.transport.write(self.wrap_message('VE', '%s %s' % (self.factory.chain.version_number, c.node_name)))
as
node_info = {'version_number':self.factory.version_number, 'node_name': c.node_name}
self.transport.write(self.wrap_message('VE', helper.json_encode(node_info) ))

which could be retrieved on other side as

node_info = helper.json_decode(data)
self.version = node_info['version_number']
printL((self.transport.getPeer().host, 'version: ', self.version))

**Comment by cyyber** [comment]
No update. Closed

**Pull request closed without merging**
