### PR TITLE
Update install instructions

### PR DESCRIPTION
**Pull request by cryptofuture**
Update install instructions

### CODE REVIEW

**Comment by cyyber** [comment]
Changing setuptools version at this line https://github.com/theQRL/QRL/blob/master/requirements.txt#L2 will solve the problem.

**Comment by cryptofuture** [comment]
@cyyber 
I doubt since:
```
File "/tmp/easy_install-5c4wuzre/PyScaffold-3.0.2/src/pyscaffold/utils.py", line 280, in check_setuptools_version
    pyscaffold.exceptions.OldSetuptools: Your setuptools version is too old (<30.3.0). Use `pip install -U setuptools` to upgrade.
```

**Comment by cyyber** [comment]
The version in requirements.txt should be setuptools>=39.0.0

**Comment by cryptofuture** [comment]
But you would need to install setuptools anyway. So if recommends enabled in the system, current guide would install python3-setuptools which is <30.3.0 in Ubuntu Xenial.
If recommends is disabled would be no setuptools installed.
So most viable option would be is to install and upgrade it. Instead of installing it directly via pip3.

**Comment by cyyber** [comment]
Accepting the PR, will remove the pip3 install from README.md and move it to requirements.txt

**Pull request merged**
