### PR TITLE
Adding test dependency on pycrypto lib

### PR DESCRIPTION
**Pull request by som-dev**
Could not run unit tests recently on a new VM due to module import failure at tests/misc/aes.py with the line "from Crypto import Random, Cipher".  Discovered pycrypto 2.6.1 already installed on base docker image but wanted to reflect this requirement in the code base in case the module is not present.

### CODE REVIEW

**Comment by cyyber** [comment]
Thanks for the PR. But I remember that I replaced pycrypto with cryptography.hazmat.primitives.ciphers.algorithms (https://github.com/theQRL/QRL/blob/master/src/qrl/crypto/AESHelper.py#L8) 

It was done as pycrypto had some vulnerability. The proper fix for this unit test is to replace pycrypto with the latest AES library.

**Review by cyyber — CHANGES_REQUESTED** [review]
Instead of adding pycrypto, better replace pycrypto with cryptography.hazmat.primitives.ciphers.algorithms in Unit test.

**Comment by som-dev** [comment]
Ok, I'll give it a try!

**Comment by som-dev** [comment]
Upon further review, no code uses the AES class in tests/misc/aes.py so does it make more sense to delete the file?

**Comment by cyyber** [comment]
> Upon further review, no code uses the AES class in tests/misc/aes.py so does it make more sense to delete the file?

Well it was earlier used for Ephemeral Messaging. The Unit test for ephemeral messaging has been deleted, so yes probably, this Unit test could be deleted too. As in the ephemeral messaging, user may use any kind of encryption to encrypt its data before broadcasting to the network.

**Review by cyyber — APPROVED** [review]

**Pull request merged**
