### PR TITLE
unit tests for core/State class

### PR DESCRIPTION
**Pull request by bmoscon**

### CODE REVIEW

**Comment by bmoscon** [comment]
@cyyber

**Comment by bmoscon** [comment]
all the failures are related to the use of assert, so I assume the "failure" in codacy is not an issue?

**Comment by jleni** [comment]
We try to use follow the recommendations when possible but they are not blocking.
In the case of asserts in tests, you can use pytest asserts and all the warnings will go away

**Comment by bmoscon** [comment]
@jleni thanks for the tip. Updated

**Pull request merged**
