### PR TITLE
Improved documentation

### PR DESCRIPTION
**Pull request by timhovius**

### CODE REVIEW

**Comment by cyyber** [comment]
branch conflict. Please recreate the pull request with latest branch.

**Comment by jleni** [comment]
Are these instructions still valid? Should be merge or close?

**Comment by surg0r** [comment]
Close

**Comment by timhovius** [comment]
It's stille valid

**Comment by surg0r** [comment]
Tim, branch conflict. Please recreate the pull request with latest branch.

**Pull request closed without merging**
